log:
  file: logs/app.log
  v115: logs/115.log
  openList: logs/openList.log
  tmdb: logs/tmdb.log
  baiduPan: logs/baidupan.log
  web: logs/web.log
  syncLogDir: logs/sync
db:
  engine: postgres
  sqliteFile: qmediasync.db
  postgresType: external
  postgresConfig:
    host: 192.168.31.94
    port: 15432
    user: qms
    password: "123123"
    database: qms_local
    maxOpenConns: 25
    maxIdleConns: 25
cacheSize: 20971520
jwtSecret: Q115-STRM-JWT-TOKEN-250706
httpHost: :12333
httpsHost: :12332
strm:
  videoExt: []
  minVideoSize: 0
  metaExt: []
  cron: ""
authServer: https://api.mqfamily.top
baiDuPanAppId: QMediaSync
adminUsername: admin
adminPassword: admin123
